#!/usr/sbin/nft -f

add table inet panther_vpn
add chain inet panther_vpn forward { type filter hook forward priority filter; policy accept; }
add table ip panther_vpn_nat
add chain ip panther_vpn_nat postrouting { type nat hook postrouting priority srcnat; policy accept; }
add rule inet panther_vpn forward iifname "ipsec0" oifname "eth0" accept
add rule inet panther_vpn forward iifname "eth0" oifname "ipsec0" ct state established,related accept
add rule ip panther_vpn_nat postrouting oifname "eth0" ip saddr 10.250.0.0/24 masquerade
