version: "3.8"

services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chirpstack

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: chirpstack
      POSTGRES_USER: chirpstack
      POSTGRES_DB: chirpstack
    restart: always

  redis:
    image: redis:7
    restart: always

  chirpstack:
    image: chirpstack/chirpstack:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    restart: always